#!/usr/bin/python3

from subprocess import Popen, DEVNULL
from socket import gethostname
from getpass import getuser
from shlex import split
from os import getcwd
import os.path
import sys

CWD = getcwd()
USER = getuser()
HOME = os.path.expanduser("~")
HOST = gethostname()


def cmd_coll(cmd):
    return cmd.format(CWD=CWD, USR=USER, HOME=HOME, HOSTN=HOST)


def exec_nonblocking(cmd):
    p = Popen(split(cmd), stdin=DEVNULL, stdout=DEVNULL,
              stderr=DEVNULL, start_new_session=True)
    return p.pid


def repeat_str(string, num, between=""):
    return between.join([string for x in range(num)])
