#!/usr/bin/python3

from socket import gethostname
from getpass import getuser
from shlex import split
from os import getcwd
import os.path
import sys

CWD = getcwd()
USER = getuser()
HOME = os.path.expanduser("~")
HOST = gethostname()


def cmd_coll(cmd):
    return cmd.format(CWD=CWD, USR=USER, HOME=HOME, HOSTN=HOST)
